---
abstract: 'translates constants back to named symbols'
author:
  - 'chromatic <chromatic@wgz.org>'
build_requires:
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Constants
requires:
  constant: 0
  strict: 0
  subs: 0
  vars: 0
resources:
  homepage: https://github.com/neilbowers/Devel-Constants
  repository: https://github.com/neilbowers/Devel-Constants.git
version: 1.02
